### ISSUE TITLE
Failure

### ISSUE THREAD

**Issue by basti88bbl** [michaelarnauts/comfoconnect#11]
Dont work at mi Pi3...

I have copy:

comfoconnect:
  host: xxx.xxx.xx.xx

and

sensor:
  - platform: comfoconnect
    resources:
      - air_flow_exhaust
      - air_flow_supply

to my configuration.yaml.

But follow message:

The following components and platforms could not be set up:
comfoconnect
comfoconnect.sensor
Please check your config.

Can you say step by step what i have to do please?

**Comment by michaelarnauts** [comment]
Please open this in the Home Assistant repository, and include the lines from your log.

**Comment by basti88bbl** [comment]
I don't unterstand?!

**Comment by michaelarnauts** [comment]
This bug should be opened in the Home Assistant repository.

You should also check the Home Assistant log for the error message.
