### ISSUE TITLE
2 and more hosts

### ISSUE THREAD

**Issue by oskartabula** [michaelarnauts/comfoconnect#13]
Hi, 
can you add ability to connect to 2 or more comfoconnect Pan Bridges? 
![Screenshot_20200106-171735_Chrome](https://user-images.githubusercontent.com/57995699/71834888-94f9d600-30b0-11ea-8739-cf239f672b18.jpg)

**Comment by michaelarnauts** [comment]
This is a change that should be handled at the Home Assistant side.
