### ISSUE TITLE
Create new tag

### ISSUE THREAD

**Issue by slootjes** [michaelarnauts/comfoconnect#15]
Can you create a new tag please?

**Comment by slootjes** [comment]
ping :)

**Comment by michaelarnauts** [comment]
For what change do you need a new release?

**Comment by slootjes** [comment]
There are tons of constants in pycomfoconnect/const.py I'd like to use in HomeAssistant but those aren't available since they were not in tag 0.3 which HA uses as the pinned version. Having the constants would make my life a lot easier to automate things. Is there anything stopping you from creating a new tag that I might be able to help with?

**Comment by michaelarnauts** [comment]
I wanted to rewrite the component in Home Assistant to use the new config flows, and by having the component check the library for supported sensors, so we don't need to declare all sensors in the home assistant component.

**Comment by slootjes** [comment]
That would be great too. Right now I'd like to have a feature to enable/disable bypass and such. If the tag would be created I could maybe contribute it to the current version of the component.

Something I tried locally (overriding the component):

    from pycomfoconnect import const as ccc

    def comfoconnect_control(call):
        command = ('cmd_'+call.data.get(ATTR_COMMAND)).upper()
        _LOGGER.error("ComfoConnect command %s", command)
        if hasattr(ccc, command):
            _LOGGER.error("ComfoConnect command %s found, sending", command)
            ccb.comfoconnect.cmd_rmi_request(getattr(ccc, command))

    hass.services.register(DOMAIN, SERVICE_COMFOCONNECT_CONTROL, comfoconnect_control)

this works really great but is pointless to add to the component since the consts aren't there in 0.3 tag.

**Comment by dkossako** [comment]
Any update on this? I can help also with HA component.

**Comment by michaelarnauts** [comment]
Sorry, no update. If you want, I could create a tag and publish an update to pypi. I haven't touched this code in some time. Feel free to update the Home Assistant component, I currently lack time/motivation to make modifications.

**Comment by dkossako** [comment]
Thanks for the reply, let's update it and then I will try to do some magic on HA side.

**Comment by michaelarnauts** [comment]
I've uploaded 0.4 to pypi.

See https://pypi.org/project/pycomfoconnect/0.4/

Feel free to make a PR for the Home Assistant component, and feel free to add your name to the code owners :)
