### ISSUE TITLE
Changing the fan speed and making the ventiation mode available

### ISSUE THREAD

**Issue by jackob007** [michaelarnauts/comfoconnect#19]
Hi!

Thanks for the integration!
I cannot create a card allowing to change the fan speed in lovelace.
Interestingly, in HomePanel, such a card is cerated automaticaly.

The second issue - is it possible to switch the ventilation mode ?

Best regards!!

Yatsek

**Comment by michaelarnauts** [comment]
There should be a `fan.ventilation` entity created, but that's an issue in Home Assistant, not with the library.
