### ISSUE TITLE
How to set value of SENSOR_FAN_NEXT_CHANGE

### ISSUE THREAD

**Issue by hanjo** [michaelarnauts/comfoconnect#22]
Hi Michaël,

do you happen to have an idea how to set the seconds for the fan next change? I believe this is used for the party mode and the vacation mode within the app. It would be cool if we could set it also it through the script. The default seems to be 7200 seconds (i.e. 2 hours).

Thanks for your code!

**Comment by michaelarnauts** [comment]
This is not possible trough the Python interface, but the commands to send are documented in case you want to modify the library. You can find more info here: https://github.com/michaelarnauts/comfoconnect/blob/master/PROTOCOL-RMI.md

**Comment by hanjo** [comment]
Thanks - I think I will just call the script to go back to automatic at the right time.

**Comment by klaudiusz223** [comment]
Hi, if You are interested, you can look at my implementation Comfoairq  Homie (MQTT). https://github.com/klaudiusz223/ComfoAirQ-Homie/.  For setting Boost (Party) mode for 
specific time in seconds look at this line `        comfoconnect.cmd_rmi_request(b'\x84\x15\x01\x06\x00\x00\x00\x00' + struct.pack('<i',value) + b'\x03')` 
https://github.com/klaudiusz223/ComfoAirQ-Homie/blob/2e5def7d98a37d53ae82536330a4b6dfda199a4f/comfoairq_homie/homie_device/device_comfoairq.py#L351
For away mode 
`comfoconnect.cmd_rmi_request(b'\x84\x15\x01\x0b\x00\x00\x00\x00' + struct.pack('<i',value) + b'\x00') `
https://github.com/klaudiusz223/ComfoAirQ-Homie/blob/2e5def7d98a37d53ae82536330a4b6dfda199a4f/comfoairq_homie/homie_device/device_comfoairq.py#L360
