### ISSUE TITLE
Missing manual command

### ISSUE THREAD

**Issue by ORi0N** [michaelarnauts/comfoconnect#3]
In de Protocol the following request is mentioned: \x83\x15\x01\x05 but the comment states that some commands are missing to actually make it switch auto->manual.
Any clue as where to go from there? 

I have tried toggling auto->manual from the android app and then tcpdumping the packets, but everything is TLS1.2 encrypted.

**Comment by michaelarnauts** [comment]
You can dump the commands, that's how I reverse engineered the basic protocol. You just need to make sure that you are on the same network as the ComfoConnect unit, otherwise, it will connect trough the internet and that is encrypted.

You can use `manually_decode.py` to decode the message into the protocol buffer output. Make sure that you dump the send and receive communications to seperate files before feeding it to `manually_decode.py`.

**Comment by ORi0N** [comment]
Ok. I guessed already as much that I needed to be on the same network to avoid SSL encryption.

I now dumped the traffic passing through the network router using:
tcpdump -i br-lan -X -vv dst port 56747 -w dump.pcap

And then try to pass this file through your 'manually_decode' but it doesn't work.
`xxx@xxx:/home/xxx/git/comfoconnect# cat dump.pcap | xxd -r -p | python3 manually_decode.py
CnRpdoRequestType
`
That's all I get out of it.

And when inspecting the traffic itself in wireshark I see the folowing data packages for AUTO->MANUAL in sequence:
```
PACKET1: 00:00:00:2f
PACKET2: f5:4c:e2:17:8f:ca:4c:29
PACKET3: a8:50:34:9f:99:69:82:6d
PACKET4: 00:00:00:00:00:19:10:11
PACKET5: 80:01:70:b3:d5:42:6d:66
PACKET6: 00:05
PACKET7: 08:21:20:e7:01
PACKET8: 08:01:12:04:**85:15:08:01**
```

packet 7 & 8:
echo "082120e701" | xxd -r -p | protoc --decode=GatewayOperation zehnder.proto
type: CnRmiRequestType
reference: 231

echo "0801120485150801" | xxd -r -p | protoc --decode=GatewayOperation zehnder.proto
type: SetAddressRequestType
2: "\205\025\010\001"

And back from MANUAL to AUTO:
```
PACKET1: 00:00:00:2f
PACKET2: f5:4c:e2:17:8f:ca:4c:29
PACKET3: a8:50:34:9f:99:69:82:6d
PACKET4: 00:00:00:00:00:19:10:11
PACKET5: 80:01:70:b3:d5:42:6d:66
PACKET6: 00:05
PACKET7: 08:21:20:e8:01
PACKET8: 08:01:12:04:**83:15:01:05**
```

echo "082120e801" | xxd -r -p | protoc --decode=GatewayOperation zehnder.proto
type: CnRmiRequestType
reference: 232

echo "0801120483150105" | xxd -r -p | protoc --decode=GatewayOperation zehnder.proto
type: SetAddressRequestType
2: "\203\025\001\005"

But I don't get what is the missing command for auto<-> manual switching. There is nothing more.

**Comment by michaelarnauts** [comment]
I'm sorry for the lack of documentation of all this, I haven't got around to writing more of it.

You can't just pass the pcap to the `manually_decode.py` script. You need the raw packets to do so. You can copy paste the HEX representation from wireshark into a text file (and make sure you remove the : seperators). Then, you can pipe that trough `xxd -r -p` to convert them back to binary format to feed it to `manually_decode.py`

If your file looks like the `captures/raw_rx.txt` file, it should work.

There is probably also a way to make tcpdump dump packets without headers, so you can skip the copy paste of the hex and the piping to xxd, but I haven't looked into that.

Regarding your packets, that is all one packet. It starts with the lenght of the packet (00:00:00:2f), followed by other lengths of other parts of the message. This part should be documented at the top of PROTOCOL.md.

You could just us the `example/examply.py` script and try to invoke `comfoconnect.cmd_rmi_request(command)` where command is the same command you see in your capture and see what happens.

I only documented some commands, but I'm fairly certain that some of the "unknown messages" return some sort of configuration or current state.

**Comment by ORi0N** [comment]
Alright, finally had some to do proper investigations. It's all one packet, which makes it easier to reverse engineer.

I've uploaded my research into the protocol.md file with some extra info.

The ones I use in my gateway file are:
`# Commands
CMD_FAN_MODE_AWAY =   b'\x84\x15\x01\x01\x00\x00\x00\x00\x01\x00\x00\x00\x00'
CMD_FAN_MODE_LOW =    b'\x84\x15\x01\x01\x00\x00\x00\x00\x01\x00\x00\x00\x01'
CMD_FAN_MODE_MEDIUM = b'\x84\x15\x01\x01\x00\x00\x00\x00\x01\x00\x00\x00\x02'
CMD_FAN_MODE_HIGH =   b'\x84\x15\x01\x01\x00\x00\x00\x00\x01\x00\x00\x00\x03'
CMD_MODE_AUTO =       b'\x85\x15\x08\x01' #AUTO !!!
CMD_MODE_MANUAL =     b'\x84\x15\x08\x01\x00\x00\x00\x00\x01\x00\x00\x00\x01' #MANUAL !!!

CMD_VENTMODE_SUPPLY = b'\x84\x15\x06\x01\x00\x00\x00\x00\x10\x0e\x00\x00\x01' ## SUPPLY ONLY !!!
CMD_VENTMODE_BALANCE =b'\x85\x15\06\01' #BALANCE MODE AGAIN !!!
CMD_TEMPPROF_NORMAL = b'\x84\x15\x03\x01\x00\x00\x00\x00\xff\xff\xff\xff\x00' # NORMAL TEMP PROFILE
CMD_TEMPPROF_COOL =   b'\x84\x15\x03\x01\x00\x00\x00\x00\xff\xff\xff\xff\x01' # COOL TEMP PROFILE
CMD_TEMPROF_WARM =    b'\x84\x15\x03\x01\x00\x00\x00\x00\xff\xff\xff\xff\x02' # WARM TEMP PROFILE
CMD_BYPASS_ON =       b'\x84\x15\x02\x01\x00\x00\x00\x00\x10\x0e\x00\x00\x01' # BYPASS ASTIVATED
CMD_BYPASS_OFF =      b'\x84\x15\x02\x01\x00\x00\x00\x00\x10\x0e\x00\x00\x02' # BYPASS DEACTIVATED
CMD_BYPASS_AUTO =     b'\x85\x15\x02\x01' # BYPASS AUTO
CMD_SENS_TEMP_OFF =   b'\x03\x1d\x01\x04\x00' # SENSOR VENT: TEMP PASSIVE OFF
CMD_SENS_TEMP_AUTO =  b'\x03\x1d\x01\x04\x01' # SENSOR VENT: TEMP PASSIVE AUTO ONLY
CMD_SENS_TEMP_ON =    b'\x03\x1d\x01\x04\x02' # SENSOR VENT: TEMP PASSIVE ON
CMD_SENS_HUMC_OFF =   b'\x03\x1d\x01\x06\x00' # SENSOR VENT: HUMIDITY COMFORT OFF
CMD_SENS_HUMC_AUTO =  b'\x03\x1d\x01\x06\x01' # SENSOR VENT: HUMIDITY COMFORT AUTO ONLY
CMD_SENS_HUMC_ON =    b'\x03\x1d\x01\x06\x02' # SENSOR VENT: HUMIDITY COMFORT ON
CMD_SENS_HUMP_OFF =   b'\x03\x1d\x01\x07\x00' # SENSOR VENT: HUMIDITY PROTECTION OFF
CMD_SENS_HUMP_AUTO =  b'\x03\x1d\x01\x07\x01' # SENSOR VENT: HUMIDITY PROTECTION AUTO
CMD_SENS_HUMP_ON =    b'\x03\x1d\x01\x07\x02' # SENSOR VENT: HUMIDITY PROTECTION ON
`

**Comment by michaelarnauts** [comment]
Cool! Thanks!

I do think some commands return more information, like `0201 0101 1503 0406 0507`. It returns the Serial Number, but I guess it also adds more information (that is encoded in the `\x00\x00\x10\x10\xc0\x02\x00T\x10@`). I haven't figured out what those additional fields can be.

**Comment by ORi0N** [comment]
Yes indeed, but I don't see the added value of those. But I think after the serial number the firmware version is displayed somehow.

I'm also looking how I can upgrade the firmware version of the ventilation unit. I've seen that there are some new versions for it already. But you need a registered installer login in order to upgrade it. Do you know someone with credentials?

**Comment by michaelarnauts** [comment]
I'm also quite certain that the commands itself have a defined structure. For example, they all seem to start with `\x84`, `\x85` or `\x03`, maybe that means something.

Also some time-based comands seem to contain the same information (boost for 30 minutes, bypass for 30 minutes, ...) I guess more commands could be called with those additional time-restrictions.

I've tried to reverse engineer the android apk, but the obfuscation made it very hard to see what command is triggered.

Feel free to create a MR with your findings and the additional commands in the `const.py`.

**Comment by michaelarnauts** [comment]
Regarding the firmware update, I also don't have that. I have firmware 1.4.0, but I've seen some users on the internet that had their supplier update their unit to 1.5.0. Unfortunately, my supplier is unable to do that. I would be glad if you could contact me if you have more luck finding those updates.

**Comment by ORi0N** [comment]
Another thing I noticed is that you have supply and exhaust mixed up:

Should be:
118 -> Supply fan duty
117 -> Exhaust fan duty

120 -> Supply fan flow
119 -> Exhaust fan flow

122 -> Supply fan speed
121 -> Exhaust fan speed

When putting it into supply only mode, you notice the wrong side drops ^^ Only noticed it now.

**Comment by michaelarnauts** [comment]
Whoops, it seems you are right :)

**Comment by michaelarnauts** [comment]
I've updated the `PROTOCOL.md` file, and documented the additional commands in the `const.py` file. Feel free to open an additional ticket if you have more updates!

Thanks a lot!
