### ISSUE TITLE
Set Bypass and Bypass time

### ISSUE THREAD

**Issue by RobZe89** [michaelarnauts/comfoconnect#30]
Hello

I would like to set Bypass on / off and the time for this to be effected. 

Thank you for your help.

**Comment by decontamin4t0R** [comment]
<img width="573" alt="image" src="https://user-images.githubusercontent.com/13054654/95609055-699c8100-0a5e-11eb-9d36-296a091669f1.png">

0x0E10 = 3600 sec = 1 hour
You need to test for yourself which timer values work, and which do not. I think that the time field is 4 bytes long, LSB encoded.

This is a RMI command, the "reference" is located at https://github.com/michaelarnauts/comfoconnect/blob/master/PROTOCOL-RMI.md

**Comment by jonesPD** [comment]
It looks like if you issue the following commands you can permanently active/deactive the bypass:



8415 0201 00000000 ffffffff 01 | Activate bypass
-- | --
8415 0201 00000000 ffffffff 02 | Deactivate bypass



Any experience with this? Suggestions?

**Comment by frank8the9tank** [comment]
How can i send these command from home assistant to open and close the bypass?
(its possible to change ventilatie "speed" with the home assistant addon that usage this library)
so the command structure should be very similar.
Can somebody then me how to add these 2 command to home assistent.
My goal is to automate the bypass based on the room temperature sensor.

**Comment by jonesPD** [comment]
You can send these commands using the `comfoconnect.cmd_rmi_request` command part of the library. I don't use home assistent so can't help you on that front.

**Comment by frank8the9tank** [comment]
Ready trough the example.py and the const.py i have seen that the command is there.
So am i correct that sending: "comfoconnect.cmd_rmi_request (CMD_BYPASS_ON)" without the"" is the correct command?
The same for closing the bypass? "comfoconnect.cmd_rmi_request (CMD_BYPASS_OFF)"

I have home assistant running and like to use these command there on the command line.
What are the complete/full command line commands for the 2 above command then?

**Comment by michaelarnauts** [comment]
As @jonesPD suggested, you can use ffffffff (-1 in signed int, little endian) to specify an unlimited timeout.

I've implemented this as a method in the [aicomfoconnect](https://github.com/michaelarnauts/aiocomfoconnect/) rewrite

See https://github.com/michaelarnauts/aiocomfoconnect/blob/master/aiocomfoconnect/comfoconnect.py#L180
