### ISSUE TITLE
Can this library be used with serial/canbus?

### ISSUE THREAD

**Issue by vekexasia** [michaelarnauts/comfoconnect#31]
Hi, it looks like you made some efforts in translating the protocol also for the canbus. I was wondering if some parts of this library could still be used coupled with a canbus transceiver somehow.

**Comment by decontamin4t0R** [comment]
Hi,

this repository is only intended to be used with the LAN C. It contains some parts of the required protocol, which, in parts is applicable to the CAN protocol. https://github.com/michaelarnauts/comfoconnect/blob/master/PROTOCOL-RMI.md is the relevant file.

I will answer also here https://github.com/marco-hoyer/zcan/issues/1 .

**Comment by michaelarnauts** [comment]
@vekexasia Indeed, there is some documentation that can be usefull, but there are other projects to use the CAN-bus directly.
