### ISSUE TITLE
Hint: Zehnder open Beta for IoT Cloud with API 

### ISSUE THREAD

**Issue by vain90** [michaelarnauts/comfoconnect#38]
Hi, 
here is a little hit.
Zehnder announced a public beta for a IoT-Cloud in december 2020.
This cloud contains some kind of API for integration into the SmartHome. 
You can find more informations here:

https://www.zehnder-systems.de/iotandvc-landing-page

**Comment by michaelarnauts** [comment]
I have registered a few weeks ago, but haven't heard anything from them.

**Comment by vain90** [comment]
I have also not yet received any feedback.
Then we have to wait patiently.

**Comment by michaelarnauts** [comment]
Installing the new version of the app causes it to upgrade the firmware of the Comfoconnect LAN C, and that gives support for more active sessions at the same time.

**Comment by rikboven** [comment]
Hey Michael,

I have the latest app in the play store, but it does not upgrade my LAN C. How do I get that to the 1.2.6?

Zehnder did come and repair my unit today (broken sensors, which seems to be common) and he upgraded the firmware of the unit, but not the LAN C.


Thanks,

Rik

**Comment by michaelarnauts** [comment]
What is the version of the app? It should be 2.0.0 (154).

I've subscribed for the beta of the app, and that gave me the update.

**Comment by rikboven** [comment]
Hey,

I'm on 1.6.2 and not on the beta. I've just registered on their beta program so hopefully they'll enable the beta in the Play store soon :)


Rik
