### ISSUE TITLE
PDID 226 shows modulation 

### ISSUE THREAD

**Issue by vain90** [michaelarnauts/comfoconnect#39]
Maybe you've already found that,
but yesterday I've seen that the PDID 226 changed after my Q350 detects more humidity and goes into "humidity control". (Comfort controls)

After a little of testing it seems that the value ist depending on which Mode you are.

Away: 0
Reduced: 100
Normal: 200
Intensive: 300

And in this modes the system can modulate.
My Q350 was in mode Normal (200) and leveled up the Airflow.

In this moment the PDID 226 shows 300 at the beginning and Reduced over time.

`200
205
206
207
206
205
200
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
214
213
212
211
210
209
208
207
206
200`

You have to read backwards.
At the same time the PDID 225 change from 1 to 2.
Maybe the 225 shows the reason for the modulation. (Comfort controls)

**Comment by vain90** [comment]
Ah, sorry didn't see the #10
My bad!

**Comment by gytisgreitai** [comment]
can you explain  more about what do you mean 'read backwards' ?

**Comment by vain90** [comment]
@gytisgreitai oh the „read backwards“ refers to my values I posted.

You have to read from back to front in order to be in the correct chronological sequence. The values I’ve posted were created when someone was just taking a shower. You can see the modulation value rises slightly at first and rises rapidly to 300. After that you can see the KWL is dissipates the increased humidity gradually.

**Comment by michaelarnauts** [comment]
Thanks all! I've added this info here: https://github.com/michaelarnauts/aiocomfoconnect/blob/master/docs/PROTOCOL-PDO.md#overview-of-known-sensors
