### ISSUE TITLE
HomeKit/Homebridge port?

### ISSUE THREAD

**Issue by fallenartist** [michaelarnauts/comfoconnect#4]
Hello! I came across this repo while searching for ways to control my Zehnder ComfoAir Q350 with Apple HomeKit via a [Homebridge](https://github.com/nfarina/homebridge) plugin (which doesn't yet exist). It looks like you've cracked most of the controls of the unit which is great. I wonder if you've ever thought of porting it for any existing home automation platform like HomeKit or know any other way to do it? I haven't found anything apart from software able to connect via KNX but that looks way OTT for my simple needs. Thanks!

**Comment by michaelarnauts** [comment]
You could use [Home Assistant](https://home-assistant.io/) (what contains a component for this library) with it's [Homekit integration](https://github.com/home-assistant/homebridge-homeassistant). I have never tried this, but I guess that should work fine.

**Comment by maciacho** [comment]
Hi, I wonder, should I have comfoconect lan to do this? I'm looking some simple device or application to manage comfoair q350 unit without comfoconect lan.

**Comment by michaelarnauts** [comment]
You need the comfoconnect lan for this library. I'm not aware of any other implementation for the comfoair q series.

**Comment by neonightmare** [comment]
does someone tried this and can confirm its working?
