### ISSUE TITLE
Setup help

### ISSUE THREAD

**Issue by suysh** [michaelarnauts/comfoconnect#43]
Hello,

I used the previous version with openhab2.5 succesfully.
Now I upgraded to openhab3 and updated to the last version of comfoconnect.
I'm missing some setup details, how to get it going.

In the previous version there was an option -d <ip-address> to discover and need to change this info into the script.
Is there somewhere more information how to setup?

Kind regards, Hans

**Comment by michaelarnauts** [comment]
Hey Hans, I don't know anything about the implementation with OpenHAB. I think there was a forum topic on the OpenHab forums about this. You I'll have more succes to find a solution there.

Also, there is no change regarding the discovery in the latest version, only some additional sensors have been added.
