### ISSUE TITLE
Activity?

### ISSUE THREAD

**Issue by decontamin4t0R** [michaelarnauts/comfoconnect#5]
Hello there,

I am currently investigating the RMI-Commands structure, because that is what primarily is usable via CAN. Is there still activity or interest in expanding this project?
I do not own a LAN bridge, but via CAN I am able to perform the RMI Commands just like you pass to the LAN bridge and receive answers.
What would be the preferred feature to look into?

**Comment by michaelarnauts** [comment]
This project is to manage the unit trough the Comfoconnect LAN C. If the RMI commands are the same, it would be great if they could be documented.

**Comment by decontamin4t0R** [comment]
As far as I can see, the commands are exactly the same, apart from being split up into messages of 7 bytes each (bc. CAN only transports 8 bytes).
If you would allow, I will make a pr in the near future to document my findings. Some are probably pretty uninteresting (like that you are able to look up the serial number with 020101011104 and with 0101011004), but I found some more PDO IDs which provide some info (67 = ComfoCool Profile (Warm, Normal, Cool), 82 = Time left for Manual Bypass State).

**Comment by michaelarnauts** [comment]
Sure, go ahead and document what you can find! Any help is welcome!

How do you find out the CAN BUS messages? Have you attached a sniffer to the bus?

**Comment by decontamin4t0R** [comment]
Part of it is reverse engineering the android app further, and some parts is just testing. I have a Raspberry Pi with a CAN-module attached to the ventilation, so I am able to try out those commands.

**Comment by michaelarnauts** [comment]
A lot of additional info can be found here: https://github.com/djwlindenaar/zcan/blob/master/mapping2.py

**Comment by decontamin4t0R** [comment]
already extended it months ago :D https://github.com/decontamin4t0R/zcan

**Comment by michaelarnauts** [comment]
Ow, cool!

**Comment by michaelarnauts** [comment]
This issue can be closed. There is an open WIP at #6
