### ISSUE TITLE
Away indicator

### ISSUE THREAD

**Issue by bedenko** [michaelarnauts/comfoconnect#52]
According to PROTOCOL-PDO.md, away_indicator should be:
| pdid | type | description                                                                                            |
|------|------|--------------------------------------------------------------------------------------------------------|
| 16   | 1    | Away indicator (`01` = low, medium, high fan speed, `07` = away) |

but i get pdid 10040001 (16) with Four bytes of increasing data (type 3 CN_UINT32).
The data seems to be some sort of clock. Increasing by 60 every minute. Current value: 0x2985a3d6

Is this my mistake, or does anyone else got this?
My device is ComfoAir Q350 with firmware R1.7.1

**Comment by NickSutton** [comment]
Is this the time that the user has put the MVHR in to 'away' mode (with the smartphone app)

**Comment by decontamin4t0R** [comment]
PDO ID 16 is only COB-ID 0x00040041. You are mixing it with 0x10040001 which is another "channel".

**Comment by michaelarnauts** [comment]
Actually, it's the device state (0=init, 1=normal, 2=filterwizard, 3=commissioning, 4=supplierfactory, 5=zehnderfactory, 6=standby, 7=away, 8=DFC).

See https://github.com/michaelarnauts/aiocomfoconnect/blob/master/docs/PROTOCOL-PDO.md#overview-of-known-sensors for an updated list.

You can also find a PDO-ID to COB-ID convertion method here: https://github.com/michaelarnauts/aiocomfoconnect/blob/master/aiocomfoconnect/util.py#L28
