### ISSUE TITLE
Zehnder ComfoFond connexion.

### ISSUE THREAD

**Issue by espeka44** [michaelarnauts/comfoconnect#57]
Anyone has already try to connect this unit with.
Some parameters changed, for example intake temp./hum. not the outdoor data. How to grab all dedicated data from this expansion module ?

**Comment by michaelarnauts** [comment]
Those sensors are available now in the new library: https://github.com/michaelarnauts/aiocomfoconnect/pull/24

**Comment by espeka44** [comment]
Hallelujah !
I will test that... when i could have a ComfoFond :)
