### ISSUE TITLE
protobuf requires update

### ISSUE THREAD

**Issue by MatthiasHertel80** [michaelarnauts/comfoconnect#58]
pip will install protobuf 4.21+ to satisfy the requirement.
Unfortunately zehnder_pb2.py will no longer be compatible and needs to be recompiled (or the requirement needs to be set to <=3.20. 

```
 File "/home/vscode/.local/lib/python3.9/site-packages/pycomfoconnect/__init__.py", line 11, in <module>
    from .comfoconnect import *
  File "/home/vscode/.local/lib/python3.9/site-packages/pycomfoconnect/comfoconnect.py", line 7, in <module>
    from .bridge import Bridge
  File "/home/vscode/.local/lib/python3.9/site-packages/pycomfoconnect/bridge.py", line 5, in <module>
    from .message import *
  File "/home/vscode/.local/lib/python3.9/site-packages/pycomfoconnect/message.py", line 4, in <module>
    from .zehnder_pb2 import *
  File "/home/vscode/.local/lib/python3.9/site-packages/pycomfoconnect/zehnder_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/home/vscode/.local/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by michaelarnauts** [comment]
I'm working on a rewrite of this library, and I took the opportunity to lean and use asyncio. The goal is to have a much cleaner API, without having to use the command strings from the const file, but simple methods with params.

I have a version running currently that is using the latest protobuf package, so this will fix this issue.

**Comment by frenck** [comment]
I've just run into this issue with the Home Assistant project.

```
pycomfoconnect==0.4
  - protobuf [required: >=3.0.0, installed: 3.20.1]
```

The required version pin suggested we could upgrade to the newer `protobuf`, but tests revealed the current `protobuf` pinned version in this library is incorrect:

```
ERROR tests/components/comfoconnect/test_sensor.py::test_sensors - TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
```

So, that makes it two problems. One is that the existing package is not pinning the top version, and the other is the need for an upgrade. For the Home Assistant project, this is a big problem/blocker. We have been working on this upgrade for a bit already, and this package came in as a surprise.

We need to upgrade to a newer `protobuf` in the short term, as it blocks the upgrade of other Google and essential core packages that provide Python 3.11 support.

Is there a possibility of releasing the current version (not the rewrite) just for the sake of a) fixing the current pinning issue and b) helping our project move forward by supporting the latest `protobuf`?

../Frenck

**Comment by michaelarnauts** [comment]
I should be able to update to the latest protobuf (version 4), I'll take a look at it.

**Comment by michaelarnauts** [comment]
Fixed in https://github.com/michaelarnauts/comfoconnect/releases/tag/0.5
