### ISSUE TITLE
AWAY Until x

### ISSUE THREAD

**Issue by blacksun80** [michaelarnauts/comfoconnect#60]
Hello, is the command for the new "AWAY bis" function already known? If you want the ventilation level e.g. B. Set it to "Away" until next week. The time program would not overwrite this function.

![grafik](https://user-images.githubusercontent.com/46262695/230866650-69544362-edb8-46bf-b86d-2f5e2f2f8dcc.png)

**Comment by michaelarnauts** [comment]
This is implemented in aiocomfoconnect. You can find this repo also in GitHub.

This library won't be further developed.
