### ISSUE TITLE
PIN not accepted when starting with "0"

### ISSUE THREAD

**Issue by ableischwitz** [michaelarnauts/comfoconnect#7]
When setting the pin to something like "0123", you will have to define that with quotes, otherwise Python will not accept this number.

```
  File "./openhab_gw.py", line 18
    pin = 0123 							# Set PIN of vent unit !
             ^
SyntaxError: invalid token
```
If you put the pin as string, the library will fail to register the app:

```
subscriber connected
publisher connected
ERROR: Could not connect to the bridge.
```

I'm using the MQTT-bridge from [here](https://github.com/ORi0N/comfoconnect_openhab_gw), but the example script **example.py** also fails.

I assume that the pin would be required to be converted into a number prior sending it to the Comfoconnect LAN C device.

**Comment by michaelarnauts** [comment]
Hmm, I have pin `0000` (default value), and the example works fine. What error do you get in the example?

In Python, you have to specify `0123` as a string like `"0123"`.

Can you change line 106 in `comfoconnect.py`
from
```py
        self._pin = pin
```
to 
```py
        self._pin = int(pin)
```
And check if it works when you define your pin like `"0123"`?

**Comment by michaelarnauts** [comment]
I assume this is an issue in https://github.com/ORi0N/comfoconnect_openhab_gw
