### ISSUE TITLE
constans 146 # Preheater power

### ISSUE THREAD

**Issue by piotrw-git** [michaelarnauts/comfoconnect#9]
Hello,
The preheater power is constant 146, while 128 is the power consumed only by ventilation

**Comment by michaelarnauts** [comment]
Thanks!

Could you check if the neigbouring constants are also defining these values for the preheater? I'm not sure if these values are kept. I don't have a preheater, so I can't tell unfortunately.

* 129: Power Consumption: Total year-to-date (1700 = 23 kWh)
* 130: Power Consumption: Total from start (1700 = 23 kWh)

I'm looking at 144 or 145. They are both 0 in my system, but maybe the value makes sense on your sysrtem.

**Comment by decontamin4t0R** [comment]
```
    144 Power_PreHeater_this_year, "kWh"
    145 Power_PreHeater_total, "kWh"
    146 Power_PreHeater_actual, "W"
```
